### PR TITLE
Fix velero_storage_settings type

### PR DESCRIPTION
**Pull request by Flow76320**
Hi ! 

There seems to be an issue when we try to override velero_storage_settings.
It's used as an object, but it defaults to the old `map(any)` type. This prevents users to override more than one parameter at a time.

This PR should fix this.
Users should be able to override all settings with, for example:
```
  velero_storage_settings = {
    name                              = mystoragename
    resource_group_name     = module.mymodule.resource_rg_name
    location                           = var.location
    account_tier                    = "Standard"
    account_replication_type = "GRS"
    tags                                = local.sometags
    allowed_cidrs                  = []
    allowed_subnet_ids         = []
    container_name              = "velero-backups"
  }
```

### CODE REVIEW

**Comment by BzSpi** [comment]
Hello @Flow76320 

Thank you very much for your contribution, we appreciate.

However, can you provide us a code example in which overriding several parameters is not possible ? We're not able to reproduce the issue.

Also, with your implementation, the user is forced to override every parameters, unless you use the [optional experimental flag](https://www.terraform.io/language/expressions/type-constraints#experimental-optional-object-type-attributes).

**Review by Shr3ps — APPROVED** [review]

**Comment by Flow76320** [comment]
Optional parameter is an option but I didn't want to add some experimental feature into that PR. LGTM

**Review by jmapro — APPROVED** [review]
LGTM

**Comment by BzSpi** [comment]
> Optional parameter is an option but I didn't want to add some experimental feature into that PR. LGTM

We tried to avoid it in the beginning also, but it's implemented since a few versions now and it's very very handy for this kind of use cases.

**Pull request merged**
