### PR TITLE
Specifies the autoscaling behaviour of the Kubernetes Cluster

### PR DESCRIPTION
**Pull request by zsteszt22**
Fixes missing property nodepools configs.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Changes proposed in this pull request

-
-
-

@claranet/fr-azure-reviewers

### CODE REVIEW

**Review by jmapro — APPROVED** [review]
LGTM

**Comment by jmapro** [comment]
Can you try to fix the documentation ? You can use pre-commit as we provide a pre-commit-config.

**Comment by zsteszt22** [comment]
I updated the README, pre-commit CI was passed

**Review by Shr3ps — APPROVED** [review]

**Review by maxpoullain — APPROVED** [review]

**Review by rossifumax — APPROVED** [review]

**Comment by Shr3ps** [comment]
Merged, released in https://github.com/claranet/terraform-azurerm-aks/releases/tag/v7.9.0

**Pull request merged**
